[build]
  functions = "netlify/functions"
  # Specify Python version as an environment variable for the build
  [build.environment]
    PYTHON_VERSION = "3.9"

# [functions] section is no longer needed for just python_version here
# If you needed other function-specific settings, it would go here,
# but python_version is now a build environment variable.